version: '3'
services:
  #Service for nameserver
  namesrv:
    image: rocketmqinc/rocketmq:4.5.0-alpine
    ports:
      - "9876:9876"
    networks:
      - backend
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: global
      restart_policy:
        condition: on-failure
#      resources:
#        limits:
#          cpus: "0.5"
#          memory: 6G
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
      - ./data/namesrv/store:/home/rocketmq/store
    command: sh mqnamesrv

  #Service for broker
  broker:
    image: rocketmqinc/rocketmq:4.5.0-alpine
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 2
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - ./data/broker/store:/home/rocketmq/store
    command: sh mqbroker -c ./conf/broker.conf

networks:
  backend: